### ISSUE TITLE
Failed to compile evdi

### ISSUE THREAD

**Issue by CodeBleu** [maggu2810/maggu2810-overlay#11]
The 'emerge --info' and 'emerge -pqv' are combined in the file attached.

Can you please help me figure out why this is not compiling?  Let me know if you need any additional info.

Files wouldnt upload as .log, so i renamed to .txt

[failed_evdi.txt](https://github.com/maggu2810/maggu2810-overlay/files/276625/failed_evdi.txt)

Here is the complete build.log file:

[build.txt](https://github.com/maggu2810/maggu2810-overlay/files/276644/build.txt)

**Comment by maggu2810** [comment]
Hello,
you are using kernel 4.6.0-gentoo.
It seems the DRM API has been changed.

So, you need to change the evdi sources to fit to the recent kernel versions.
http://www.displaylink.org/forum/showthread.php?p=80023

As stated already somewhere else, I do not use this stuff anymore.
Perhaps I should remove the ebuild.

**Comment by maggu2810** [comment]
It seems also to be solved upstream. Perhaps I will bump the ebuilds if I have some spare time.

**Comment by maggu2810** [comment]
I have not tried it myself, but you can do a fresh sync and try to install evdi and display link again.

**Comment by CodeBleu** [comment]
After a fresh sync, I was able to install evdi and displaylink-driver without issue.  Thanks!  However, I'm not sure if you can help me with this or not, but I'm able to get the 'provideroutputsource' and am able to set it to my laptop monitor.  I then go into arandr to enable the monitor and set resolution.  This makes the external monitor 'connect' and changes the light from amber to green, but the screen is blank.  Do you have any ideas why this would be happening?

**Comment by maggu2810** [comment]
Sorry that I cannot help you.
I assume you should post your question here: http://displaylink.org/forum/forumdisplay.php?f=29

**Comment by CodeBleu** [comment]
Thanks for your help!
