### ISSUE TITLE
Manifest removals

### ISSUE THREAD

**Issue by NP-Hardass** [maggu2810/maggu2810-overlay#16]
Hey, just wondering why you removed all manifests... Makes it hard to run qa tools because distfiles manifests are expected, at a minimum.  Thoughts on thin-manifests = true instead of use-manifests = false?

**Comment by maggu2810** [comment]
Hi,
I removed it because the different changes in the manifest (e.g. MD5 sums) results into merge conflicts multiple times.
As I am not using Gentoo anymore, this overlay is not really moved forward by me.

**Comment by NP-Hardass** [comment]
> Hi,
> I removed it because the different changes in the manifest (e.g. MD5 sums) results into merge conflicts multiple times.
> As I am not using Gentoo anymore, this overlay is not really moved forward by me.

OK. Thanks for the info.
