### ISSUE TITLE
Bump request for app-misc/mosquitto

### ISSUE THREAD

**Issue by destroyedlolo** [maggu2810/maggu2810-overlay#8]
Hello,

Is it possible to bump app-misc/mosquitto to the latest version (1.4.4 as time of writing) ?

I'm facing some memory corruption / crash and I suspect Mosquitto doesn't handle correctly incorrect requests.

Thanks

Laurent

**Comment by maggu2810** [comment]
Hello,

I have done a bump. Please test it suffers your needs.

Best regards,
Markus

2015-10-12 16:21 GMT+02:00 destroyedlolo <notifications@github.com>:

**Comment by destroyedlolo** [comment]
Compile like a charm on my BananaPI ARM system. Thanks a lot.

Bye

Laurent
